// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAriAcjJzlNigP89wQhi8OYefXlWQSHgho',
    appId: '1:265296041362:web:cc34a4335e3a4677169d4b',
    messagingSenderId: '265296041362',
    projectId: 'loja01-f607f',
    authDomain: 'loja01-f607f.firebaseapp.com',
    storageBucket: 'loja01-f607f.appspot.com',
    measurementId: 'G-8JSKS9YJGW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJPmZGPjQfc5kXU0PBiEDXxmzOURw0FV8',
    appId: '1:265296041362:android:40a4dbf8f5c97f78169d4b',
    messagingSenderId: '265296041362',
    projectId: 'loja01-f607f',
    storageBucket: 'loja01-f607f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEVeOrT7gxrPJRVIhEzhd4JGXKgO2kZCo',
    appId: '1:265296041362:ios:a3bc57c92332d827169d4b',
    messagingSenderId: '265296041362',
    projectId: 'loja01-f607f',
    storageBucket: 'loja01-f607f.appspot.com',
    iosClientId: '265296041362-lesv04ekp7go9ko0cesvfm25vp5t8b7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.loja01',
  );
}
